name: Flutter Code Health CI

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Check code formatting
        run: dart format --set-exit-if-changed .

  dependency_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Audit dependencies for known vulnerabilities (requires `pana` package)
        run: |
          dart pub global activate pana
          pana --no-warning --exit-code-if-not-clean

  smoke_build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Build web (smoke test)
        run: flutter build web --release --no-sound-null-safety